# Generated by Django 5.0.2 on 2025-03-01 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ram', models.CharField(max_length=50)),
                ('rom', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='phones/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phones.phonecompany')),
            ],
        ),
    ]
