# Generated by Django 5.0.2 on 2025-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo',
            field=models.URLField(max_length=2000),
        ),
    ]
