# Generated by Django 5.0.2 on 2025-03-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_phone_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='photo',
            field=models.URLField(max_length=4000),
        ),
    ]
